const initCurrencies = {
  "AED": {"code": "AED", "name": "United Arab Emirates Dirham"},
  "AFN": {"code": "AFN", "name": "Afghan Afghani"},
  "ALL": {"code": "ALL", "name": "Albanian Lek"},
  "AMD": {"code": "AMD", "name": "Armenian Dram"},
  "ANG": {"code": "ANG", "name": "Netherlands Antillean Guilder"},
  "AOA": {"code": "AOA", "name": "Angolan Kwanza"},
  "ARS": {"code": "ARS", "name": "Argentine Peso"},
  "AUD": {"code": "AUD", "name": "Australian Dollar"},
  "AWG": {"code": "AWG", "name": "Aruban Florin"},
  "AZN": {"code": "AZN", "name": "Azerbaijani Manat"},
  "BAM": {"code": "BAM", "name": "Bosnia and Herzegovina Convertible Mark"},
  "BBD": {"code": "BBD", "name": "Barbadian Dollar"},
  "BDT": {"code": "BDT", "name": "Bangladeshi Taka"},
  "BGN": {"code": "BGN", "name": "Bulgarian Lev"},
  "BHD": {"code": "BHD", "name": "Bahraini Dinar"},
  "BIF": {"code": "BIF", "name": "Burundian Franc"},
  "BMD": {"code": "BMD", "name": "Bermudian Dollar"},
  "BND": {"code": "BND", "name": "Brunei Dollar"},
  "BOB": {"code": "BOB", "name": "Bolivian Boliviano"},
  "BRL": {"code": "BRL", "name": "Brazilian Real"},
  "BSD": {"code": "BSD", "name": "Bahamian Dollar"},
  "BTN": {"code": "BTN", "name": "Bhutanese Ngultrum"},
  "BWP": {"code": "BWP", "name": "Botswana Pula"},
  "BYN": {"code": "BYN", "name": "Belarusian Ruble"},
  "BZD": {"code": "BZD", "name": "Belize Dollar"},
  "CAD": {"code": "CAD", "name": "Canadian Dollar"},
  "CDF": {"code": "CDF", "name": "Congolese Franc"},
  "CHF": {"code": "CHF", "name": "Swiss Franc"},
  "CKD": {"code": "CKD", "name": "Cook Islands Dollar"},
  "CLP": {"code": "CLP", "name": "Chilean Peso"},
  "CNY": {"code": "CNY", "name": "Chinese Yuan"},
  "COP": {"code": "COP", "name": "Colombian Peso"},
  "CRC": {"code": "CRC", "name": "Costa Rican Colon"},
  "CUC": {"code": "CUC", "name": "Cuban convertible Peso"},
  "CUP": {"code": "CUP", "name": "Cuban Peso"},
  "CVE": {"code": "CVE", "name": "Cabo Verdean Escudo"},
  "CZK": {"code": "CZK", "name": "Czech Koruna"},
  "DJF": {"code": "DJF", "name": "Djiboutian Franc"},
  "DKK": {"code": "DKK", "name": "Danish Krone"},
  "DOP": {"code": "DOP", "name": "Dominican Peso"},
  "DZD": {"code": "DZD", "name": "Algerian Dinar"},
  "EGP": {"code": "EGP", "name": "Egyptian Pound"},
  "EHP": {"code": "EHP", "name": "Sahrawi Peseta"},
  "ERN": {"code": "ERN", "name": "Eritrean Nakfa"},
  "ETB": {"code": "ETB", "name": "Ethiopian Birr"},
  "EUR": {"code": "EUR", "name": "Euro"},
  "FJD": {"code": "FJD", "name": "Fijian Dollar"},
  "FKP": {"code": "FKP", "name": "Falkland Islands Pound"},
  "FOK": {"code": "FOK", "name": "Faroese Króna"},
  "GBP": {"code": "GBP", "name": "Pound Sterling"},
  "GEL": {"code": "GEL", "name": "Georgian Lari"},
  "GGP": {"code": "GGP", "name": "Guernsey Pound"},
  "GHS": {"code": "GHS", "name": "Ghanaian Cedi"},
  "GIP": {"code": "GIP", "name": "Gibraltar Pound"},
  "GMD": {"code": "GMD", "name": "Gambian Dalasi"},
  "GNF": {"code": "GNF", "name": "Guinean Franc"},
  "GTQ": {"code": "GTQ", "name": "Guatemalan Quetzal"},
  "GYD": {"code": "GYD", "name": "Guyanese Dollar"},
  "HKD": {"code": "HKD", "name": "Hong Kong Dollar"},
  "HNL": {"code": "HNL", "name": "Honduran Lempira"},
  "HRK": {"code": "HRK", "name": "Croatian Kuna"},
  "HTG": {"code": "HTG", "name": "Haitian Gourde"},
  "HUF": {"code": "HUF", "name": "Hungarian Forint"},
  "IDR": {"code": "IDR", "name": "Indonesian Rupiah"},
  "ILS": {"code": "ILS", "name": "Israeli new Shekel"},
  "IMP": {"code": "IMP", "name": "Manx Pound"},
  "INR": {"code": "INR", "name": "Indian Rupee"},
  "IQD": {"code": "IQD", "name": "Iraqi Dinar"},
  "IRR": {"code": "IRR", "name": "Iranian Rial"},
  "ISK": {"code": "ISK", "name": "Icelandic Krona"},
  "JEP": {"code": "JEP", "name": "Jersey Pound"},
  "JMD": {"code": "JMD", "name": "Jamaican Dollar"},
  "JOD": {"code": "JOD", "name": "Jordanian Dinar"},
  "JPY": {"code": "JPY", "name": "Japanese Yen"},
  "KES": {"code": "KES", "name": "Kenyan Shilling"},
  "KGS": {"code": "KGS", "name": "Kyrgyzstani Som"},
  "KHR": {"code": "KHR", "name": "Cambodian Riel"},
  "KID": {"code": "KID", "name": "Kiribati Dollar"},
  "KMF": {"code": "KMF", "name": "Comorian Franc"},
  "KPW": {"code": "KPW", "name": "North Korean Won"},
  "KRW": {"code": "KRW", "name": "South Korean Won"},
  "KWD": {"code": "KWD", "name": "Kuwaiti Dinar"},
  "KYD": {"code": "KYD", "name": "Cayman Islands Dollar"},
  "KZT": {"code": "KZT", "name": "Kazakhstani Tenge"},
  "LAK": {"code": "LAK", "name": "Lao Kip"},
  "LBP": {"code": "LBP", "name": "Lebanese Pound"},
  "LKR": {"code": "LKR", "name": "Sri Lankan Rupee"},
  "LRD": {"code": "LRD", "name": "Liberian Dollar"},
  "LSL": {"code": "LSL", "name": "Lesotho Loti"},
  "LYD": {"code": "LYD", "name": "Libyan Dinar"},
  "MAD": {"code": "MAD", "name": "Moroccan Dirham"},
  "MDL": {"code": "MDL", "name": "Moldovan Leu"},
  "MGA": {"code": "MGA", "name": "Malagasy Ariary"},
  "MKD": {"code": "MKD", "name": "Macedonian Denar"},
  "MMK": {"code": "MMK", "name": "Myanmar Kyat"},
  "MNT": {"code": "MNT", "name": "Mongolian Tögrög"},
  "MOP": {"code": "MOP", "name": "Macanese Pataca"},
  "MRU": {"code": "MRU", "name": "Mauritanian Ouguiya"},
  "MUR": {"code": "MUR", "name": "Mauritian Rupee"},
  "MVR": {"code": "MVR", "name": "Maldivian Rufiyaa"},
  "MWK": {"code": "MWK", "name": "Malawian Kwacha"},
  "MXN": {"code": "MXN", "name": "Mexican Peso"},
  "MYR": {"code": "MYR", "name": "Malaysian Ringgit"},
  "MZN": {"code": "MZN", "name": "Mozambican Metical"},
  "NAD": {"code": "NAD", "name": "Namibian Dollar"},
  "NGN": {"code": "NGN", "name": "Nigerian Naira"},
  "NIO": {"code": "NIO", "name": "Nicaraguan Córdoba"},
  "NOK": {"code": "NOK", "name": "Norwegian Krone"},
  "NPR": {"code": "NPR", "name": "Nepalese Rupee"},
  "NZD": {"code": "NZD", "name": "New Zealand Dollar"},
  "OMR": {"code": "OMR", "name": "Omani Rial"},
  "PAB": {"code": "PAB", "name": "Panamanian Balboa"},
  "PEN": {"code": "PEN", "name": "Peruvian Sol"},
  "PGK": {"code": "PGK", "name": "Papua New Guinean Kina"},
  "PHP": {"code": "PHP", "name": "Philippine Peso"},
  "PKR": {"code": "PKR", "name": "Pakistani Rupee"},
  "PLN": {"code": "PLN", "name": "Polish Zloty"},
  "PND": {"code": "PND", "name": "Pitcairn Islands Dollar"},
  "PRB": {"code": "PRB", "name": "Transnistrian Ruble"},
  "PYG": {"code": "PYG", "name": "Paraguayan Guaraní"},
  "QAR": {"code": "QAR", "name": "Qatari Riyal"},
  "RON": {"code": "RON", "name": "Romanian Leu"},
  "RSD": {"code": "RSD", "name": "Serbian Dinar"},
  "RUB": {"code": "RUB", "name": "Russian Ruble"},
  "RWF": {"code": "RWF", "name": "Rwandan Franc"},
  "SAR": {"code": "SAR", "name": "Saudi Riyal"},
  "SBD": {"code": "SBD", "name": "Solomon Islands Dollar"},
  "SCR": {"code": "SCR", "name": "Seychellois Rupee"},
  "SDG": {"code": "SDG", "name": "Sudanese Pound"},
  "SEK": {"code": "SEK", "name": "Swedish Krona"},
  "SGD": {"code": "SGD", "name": "Singapore Dollar"},
  "SHP": {"code": "SHP", "name": "Saint Helena Pound"},
  "SLE": {"code": "SLE", "name": "Sierra Leonean Leone"},
  "SLL": {"code": "SLL", "name": "Sierra Leonean Leone (old)"},
  "SLS": {"code": "SLS", "name": "Somaliland Shilling"},
  "SOS": {"code": "SOS", "name": "Somali Shilling"},
  "SRD": {"code": "SRD", "name": "Surinamese Dollar"},
  "SSP": {"code": "SSP", "name": "South Sudanese Pound"},
  "STN": {"code": "STN", "name": "Sao Tome and Príncipe Dobra"},
  "SVC": {"code": "SVC", "name": "Salvadoran Colón"},
  "SYP": {"code": "SYP", "name": "Syrian Pound"},
  "SZL": {"code": "SZL", "name": "Swazi Lilangeni"},
  "THB": {"code": "THB", "name": "Thai Baht"},
  "TJS": {"code": "TJS", "name": "Tajikistani Somoni"},
  "TMT": {"code": "TMT", "name": "Turkmenistan Manat"},
  "TND": {"code": "TND", "name": "Tunisian Dinar"},
  "TOP": {"code": "TOP", "name": "Tongan Paʻanga"},
  "TRY": {"code": "TRY", "name": "Turkish Lira"},
  "TTD": {"code": "TTD", "name": "Trinidad and Tobago Dollar"},
  "TVD": {"code": "TVD", "name": "Tuvaluan Dollar"},
  "TWD": {"code": "TWD", "name": "New Taiwan Dollar"},
  "TZS": {"code": "TZS", "name": "Tanzanian Shilling"},
  "UAH": {"code": "UAH", "name": "Ukrainian Hryvnia"},
  "UGX": {"code": "UGX", "name": "Ugandan Shilling"},
  "USD": {"code": "USD", "name": "United States Dollar"},
  "UYU": {"code": "UYU", "name": "Uruguayan Peso"},
  "UZS": {"code": "UZS", "name": "Uzbekistani Som"},
  "VED": {"code": "VED", "name": "Venezuelan bolívar digital"},
  "VES": {"code": "VES", "name": "Venezuelan Bolívar Soberano"},
  "VND": {"code": "VND", "name": "Vietnamese Dong"},
  "VUV": {"code": "VUV", "name": "Vanuatu Vatu"},
  "WST": {"code": "WST", "name": "Samoan Tala"},
  "XAF": {"code": "XAF", "name": "Central African CFA Franc BEAC"},
  "XCD": {"code": "XCD", "name": "East Caribbean Dollar"},
  "XCG": {"code": "XCD", "name": "Caribbean guilder"},
  "XDR": {"code": "XCD", "name": "Special drawing rights"},
  "XOF": {"code": "XOF", "name": "West African CFA Franc BCEAO"},
  "XPF": {"code": "XPF", "name": "CFP Franc (Franc Pacifique)"},
  "YER": {"code": "YER", "name": "Yemeni Rial"},
  "ZAR": {"code": "ZAR", "name": "South African Rand"},
  "ZMW": {"code": "ZMW", "name": "Zambian Kwacha"},
  "ZWB": {"code": "ZWB", "name": "RTGS Dollar"},
  "ZWL": {"code": "ZWL", "name": "Zimbabwean Dollar"},
};
